version: 2
enable-beta-ecosystems: true

updates:
  # Apps
  - package-ecosystem: pub
    directory: .
    schedule:
      interval: daily
      time: "04:00"
      timezone: "Asia/Ho_Chi_Minh"
    reviewers:
      - kietapvn
    versioning-strategy: increase
    open-pull-requests-limit: 1
