name: PR
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, edited]
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Install packages
        run: flutter pub get && flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Lint
        run: flutter analyze
      - name: Test
        run: flutter test
